#############################################################################
# Makefile for building: usingQtDesigner.app/Contents/MacOS/usingQtDesigner
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  usingQtDesigner.pro
# Template: app
# Command: /Users/Dimitar/Qt/5.8/clang_64/bin/qmake -o usingQtDesigner.xcodeproj/project.pbxproj usingQtDesigner.pro -spec macx-xcode
#############################################################################

MAKEFILE      = project.pbxproj

QMAKE    = /Users/Dimitar/Qt/5.8/clang_64/bin/qmake
usingQtDesigner.xcodeproj/project.pbxproj: usingQtDesigner.pro /Users/Dimitar/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf /Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/qdevice.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/device_config.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/unix.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/mac.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/macx.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/sanitize.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/clang.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/qconfig.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qt_config.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/macx-xcode/qmake.conf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/toolchain.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/default_pre.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/default_post.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/warn_on.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qt.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/resources.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/moc.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/uic.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/file_copies.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/exceptions.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/yacc.prf \
		/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/lex.prf \
		usingQtDesigner.pro \
		ref_images.qrc \
		/Users/Dimitar/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/Dimitar/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/Dimitar/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o usingQtDesigner.xcodeproj/project.pbxproj usingQtDesigner.pro -spec macx-xcode
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/spec_pre.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/qdevice.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/device_config.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/unix.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/mac.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/macx.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/sanitize.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/gcc-base.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/clang.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/common/clang-mac.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/qconfig.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qt_functions.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qt_config.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/macx-xcode/qmake.conf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/sdk.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/toolchain.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/default_pre.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/resolve_config.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/default_post.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/default_post.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/warn_on.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qt.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/resources.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/moc.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/unix/opengl.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/uic.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/unix/thread.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/qmake_use.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/file_copies.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/rez.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/testcase_targets.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/exceptions.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/yacc.prf:
/Users/Dimitar/Qt/5.8/clang_64/mkspecs/features/lex.prf:
usingQtDesigner.pro:
ref_images.qrc:
/Users/Dimitar/Qt/5.8/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/Dimitar/Qt/5.8/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/Dimitar/Qt/5.8/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o usingQtDesigner.xcodeproj/project.pbxproj usingQtDesigner.pro -spec macx-xcode

qmake_all: FORCE

